# Generated by Django 4.2.1 on 2023-05-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('poster_url', models.URLField()),
                ('title', models.TextField()),
                ('imdb_url', models.URLField()),
            ],
        ),
    ]
